backend:
  name: git-gateway
  branch: main
  login: true

media_folder: "images/uploads"
public_folder: "/images/uploads"

collections:
  - name: "pages"
    label: "Pages"
    files:
      - label: "Privacy Policy"
        name: "privacy"
        file: "privacy.html"
        fields:
          - { label: "Page Title", name: "title", widget: "string" }
          - { label: "Content", name: "body", widget: "markdown" }
